<?php

namespace Database\Seeders\Custom;

use App\Services\PlanService;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class Seeder1683629501 extends Seeder
{
    public function run()
    {
        $plans = [
            //monthly
            [
                'name' => 'Xme Demo',
                'type' => 'free',
                'price' => 0,
                "members" => 0,
                "company_admin" => 1,
                'company_sub_admin' => 0,
                'total_users' => 1,
                "disk_storage" => 1000,
                'api_rate_limit' => 60,
                'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 1,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'Xme 3 Demo',
                'type' => 'xme-3-demo-monthly',
                'price' => 10.45,
                    "members" => 2,
                    "company_admin" => 1,
                    'company_sub_admin' => 2,
                    'total_users' => 3,
                    "disk_storage" => 3000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 1,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'XME 10 Plan',
                'type' => 'xme-10-plan-monthly',
                'price' => 92.40,
                    "members" => 9,
                    "company_admin" => 1,
                    'company_sub_admin' => 9,
                    'total_users' => 10,
                    "disk_storage" => 10000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 1,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'XME 25 Plan',
                'type' => 'xme-25-plan-monthly',
                'price' => 184.80,
                    "members" => 24,
                    "company_admin" => 1,
                    'company_sub_admin' => 24,
                    'total_users' => 25,
                    "disk_storage" => 25000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 1,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'XME 50 Plan',
                'type' => 'xme-50-plan-monthly',
                'price' => 308.55,
                    "members" => 49,
                    "company_admin" => 1,
                    'company_sub_admin' => 49,
                    'total_users' => 50,
                    "disk_storage" => 50000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 1,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'XME 75 Plan',
                'type' => 'xme-75-plan-monthly',
                'price' => 411.40,
                    "members" => 74,
                    "company_admin" => 1,
                    'company_sub_admin' => 74,
                    'total_users' => 75,
                    "disk_storage" => 75000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 1,
                'valid_from' => Carbon::now(),
            ],
            //yearly
            [
                'name' => 'Xme 3 Demo',
                'type' => 'xme-3-demo-yearly',
                'price' => 25.65,
                    "members" => 2,
                    "company_admin" => 1,
                    'company_sub_admin' => 2,
                    'total_users' => 3,
                    "disk_storage" => 10000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 2,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'Xme 10 Demo',
                'type' => 'xme-10-demo-yearly',
                'price' => 75.60,
                   "members" => 9,
                    "company_admin" => 1,
                    'company_sub_admin' => 9,
                    'total_users' => 10,
                    "disk_storage" => 10000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 2,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'Xme 25 Demo',
                'type' => 'xme-25-demo-yearly',
                'price' => 151.20,
                    "members" => 24,
                    "company_admin" => 1,
                    'company_sub_admin' => 24,
                    'total_users' => 25,
                    "disk_storage" => 25000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 2,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'Xme 50 Demo',
                'type' => 'xme-50-demo-yearly',
                'price' => 252.45,
                    "members" => 49,
                    "company_admin" => 1,
                    'company_sub_admin' => 49,
                    'total_users' => 50,
                    "disk_storage" => 50000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 2,
                'valid_from' => Carbon::now(),
            ],
            [
                'name' => 'Xme 75 Demo',
                'type' => 'xme-75-demo-yearly',
                'price' => 336.60,
                    "members" => 74,
                    "company_admin" => 1,
                    'company_sub_admin' => 74,
                    'total_users' => 75,
                    "disk_storage" => 75000,
                    'api_rate_limit' => 60,
                    'api_quota_limit' => 60,
                'stripe_plan_id' => null,
                'interval' => 2,
                'valid_from' => Carbon::now(),
            ]
        ];
        foreach ($plans as $plan) {
            $planService = new PlanService();
            $planService->store($plan);
        }
    }
}
